gcanti/fp-ts

src/function.ts

use the same generic type scheme for `curry`
this happens to be a breaking change when `compose` is used with 5 or more functions, but actual return type would have been different from inferred type.

fix: fix compose generic type positions

---

src/Option.ts
test/Option.ts

Hi. I'm switch a project over from flow and flow-static-land to ts and fp-ts. In updating a section that used `Maybe` from flow-static-land to use `Option`, i noticed that the behaviour changed. It looks to me like `reduce` on `Some` isn't quite right, as it never calls `f`. This is different to how it was in flow-static-land. Is that intentional and should I be using `fold` directly instead? 
I'm still very much in the training-wheels phase with a lot of this stuff, but it strikes me that `reduce` and `fold` do very similar things. When should one be used over the other? Is it just that `reduce` should be used when you don't want to have to deal with converting to `Lazy<A>` yourself?

fix Some.reduce so it calls f

---

src/Array.ts
src/function.ts
test/Array.ts
test/function.ts

@sledorze I'm not sure how the `and` combinator could be useful in the case of custom guards, have you got a compelling example?

add refinements, closes #68

---

src/Applicative.ts
src/Apply.ts
src/Array.ts
src/Chain.ts
src/Contravariant.ts
src/Either.ts
src/EitherT.ts
src/Extend.ts
src/Filterable.ts
src/Foldable.ts
src/Free.ts
src/Functor.ts
src/HKT.ts
src/Identity.ts
src/NonEmptyArray.ts
src/Option.ts
src/OptionT.ts
src/ReaderT.ts
src/StateT.ts
src/StrMap.ts
src/These.ts
src/Traversable.ts
src/Validation.ts
src/Witherable.ts

Here's the POC for HKTAs. It's a very simple replacement for URI2HKT. It's just a bit more typesafe (forces use of HKTS) and stops you from using wrongly defined URI2HKT mappings. It also means users don't have to use indexers anymore, but just plain generics, to access the URI2HKT map.

Added integrity checking and HKTAs

---

src/Filterable.ts
src/Option.ts
src/Witherable.ts

As promised. Array doesn't have Fantasy* implementations and Either needs a monoid to be available to do them, so only Option.ts is changed to reflect the new interfaces.

FantasyFilterable and FantasyWitherable

---

src/Foldable.ts
src/Ord.ts
src/Profunctor.ts
src/Unfoldable.ts

Legend:
- TCR: type constraint rule: all type constraints are grouped together
- TI: currying will cause bad type inference
- TU: is not curried because of the typical usage
Functions
- `Applicative.getApplicativeComposition` Won't fix: TCR
- `Apply.ap` Won't fix: TI
- `Bifunctor.bimap` Won't fix: TU
- `Chain.chain` Won't fix: TI
- `ChainRec.chainRec` Won't fix: TI
- `ChainRec.tailRec` Won't fix: TI
- `Either.fromPredicate` Won't fix: TU
- `Extend.extend` Won't fix: TI
- `Filterable.partitionMap` Won't fix: TI
- `Foldable.reduce` Won't fix: TI
- `Foldable.getFoldableComposition` Won't fix: TCR
- `Foldable.foldMap` Won't fix: TCR
- `Foldable.foldr` **fixed**
- `Foldable.intercalate` Won't fix: TCR
- `Foldable.traverse_` Won't fix: TCR
- `Foldable.sequence_` Won't fix: TCR
- `Functor.map` …

The Quest of uncurried functions

---

package.json
src/EitherT.ts

As discussed, Monad<F> is required to be able to recreate F after it runs.

Fixes #219 EitherT doesn't play nice with Task 

---

src/TaskEither.ts
src/index.ts

This PR promotes `TaskEither` from the examples to the std lib

add TaskEither

---

src/Either.ts
test/Either.ts

This PR changes `getOrElse` signature and implementation of `Either`, allowing the callback to receive the `Left` value but nevertheless keeping backward compatibility.
Note: this will diverge from Scala typings for `Either.getOrElse` but it's useful for behaviours depending on the `Left` value

Either: pass value to `getOrElse`

---

src/Option.ts
test/Option.ts

This PR adds a handy shortcut to `map(f).chain(fromNullable)` which is useful when working with deep optional structures.

add Option#mapNullable

---

src/function.ts

This PR adds two thunks to function.ts - constNull and constUndefined.
They are pretty useful when folding options in React TSX:
```typescript
type Props = {
value: Option<number>
}
const Value: SFC<Props> = ({value}) => value.fold(constNull, value => (
<div>Value: {value}</div>
))
```

add constNull and constUndefined

---

src/Either.js.flow

Found a duplicate definition for the fold signature of Either (Flow). This microfix just removes it.

Removed duplicate fold definition from Either

---

src/Either.ts
src/Option.js.flow
src/Option.ts
test/Option.ts

This will remove an unnecessary runtime dependency in the next breaking change release

deprecate toOption in Either in favour of fromEither in Option

---

docs/api/md/Array.md
src/Array.ts
test/Array.ts

Hi, 
I've observed that in haskell/scala they have a scan function which allows to do a fold carrying intermediate steps and I've translated the haskell implementation to TS.
http://hackage.haskell.org/package/base-4.10.1.0/docs/src/GHC.List.html#scanl
https://github.com/scala/collection-strawman/blob/57340b9fa6732a0bae37845f16dfb272fbb2173a/collections/src/main/scala/strawman/collection/immutable/LazyList.scala#L271

Add scan left/right functions

---

package-lock.json
package.json

`rm -rf` doesn't work on windows, so this PR adds [shx](https://www.npmjs.com/package/shx) as a dev dependency and uses it in the `clean` and `docs` npm scripts.

Add shx and update npm scripts to allow building on Windows

---

src/NonEmptyArray.ts
test/NonEmptyArray.ts

adds `last` shortcut method to NonEmptyArray
PS. Seems odd to increase minor version in `@since` jsdoc tag each time a small helper is added. What can we do with this?

feature: add NonEmptyArray.prototype.last

---

src/NonEmptyArray.ts

covers `NonEmptyArray` public methods/functions with jsdoc

docs: NonEmptyArray

---

src/ReaderTaskEither.ts
src/TaskEither.ts
test/ReaderTaskEither.ts

- change `run`
- add `applyFirst`, `applySecond` methods
- remove `fromTask` in favour of `right`
- add `fromIO`, `fromLeft`, `fromIOEither` lifting functions

Refactor ReaderTaskEither

---

src/ReaderTaskEither.ts
test/ReaderTaskEither.ts

My spider sense is tingling about having to do `.run({}).run()` in the tests, but I can't see a better return type than `Reader<E, Task<R>>` so....

add fold to ReaderTaskEither

---

src/TaskEither.ts
test/TaskEither.ts

When wrapping a function from elasticsearch client the callback is called with `undefined` as first argument preventing taskify to return a right and instead returns left

Handle undefined errors in callback of TaskEither taskify

---

package.json
src/Option.ts
test/Option.ts
typings-checker/index.ts

This function can be used to ensure that a custom type definition is type safe.
Example
```ts
type A = { type: 'A' }
type B = { type: 'B' }
type C = A | B
const isA = (c: C): c is A => c.type === 'B' // <= typo but typescript doesn't complain
const isA = getRefinement<C, A>(c => (c.type === 'B' ? some(c) : none)) // static error: Type '"B"' is not assignable to type '"A"'
```
The trick is to force typescript to check that the refinement is correct in `c.type === 'B' ? some(c) : none`

New Feature: add Option.getRefinement

---

src/Foldable.ts
test/Foldable.ts

@sledorze @raveclassic when releasing `fp-ts@1.0.0` I forgot to swap the arguments of `Foldable.traverse_`. This PR adds a `traverse` function with better argument order and deprecates `traverse_`

New Feature: add Foldable.traverse and deprecate traverse_

---

package-lock.json
package.json
tsconfig.json

I considered two ways to do this:
1. Change the `files` array to: `["lib/**/*.js", "lib/**/*.d.ts"]`.
2. Do not emit the sourcemaps when publishing to npm.
I went with the second choice to avoid having to update the `files` array if there was every anything else in `lib/` that needed to be included in the future. This also seems to more directly target the issue: don't publish the sourcemaps.
Also updated the package version in the `package-lock.json` which was surprising that it was not in-sync with the `package.json` value. 🤷‍♂️ 
**Not addressed in this PR**: The module structure has not changed, so `fp-ts/lib/Foo` is still the way to import sub-modules.
<details>
<summary>The output of <code>npm pack --dry-run</code>:</summary>
<br>
```
npm notice 
npm notice 📦  fp-ts@1.8.1
npm notice …
```

Skip emitting sourcemaps when publishing to npm

---

docs/Array.md
src/Array.ts

Hey there!
My team just started using this lib and I saw in #265 that you're taking PRs to help
improve the docs. I personally would love some examples for functions like `member` so
I thought I'd add one.
I'll be sure to throw up more PRs of examples as I go.
Great library!

Add example to docs for Array.member function

---

package-lock.json
package.json

Adding `ts-node` as dependency. It's missing, but used here: https://github.com/gcanti/fp-ts/blob/6d48327c5e9e12d1e68d9856a9a7fb72a3f3aee2/package.json#L21

TS node dependency

---

src/TaskEither.ts
test/TaskEither.ts

`taskify` mutates the `args` adding a callback every time the task runs, causing the wrapping promise not being resolved. This PR fixes this behaviour.

Fix taskify with immutable arguments.

---

src/ReaderTaskEither.ts

Now `tryCatch` from `ReaderTaskEither` pass the reader's value as the second argument to `onrejected` function.

Pass read value to 'onrejected' handler for ReaderTaskEither's tryCatch

---

src/FunctorWithIndex.ts

I think this was a mistake. Just correcting what appeared to be a typo.

FunctorWithIndex comment typo fix: `map` -> `mapWithIndex`

---

docs/function.md
src/function.ts
test/function.ts

Sometimes, only a `void` will do. Here's a companion to `constUndefined` et al that returns `void`.

Added constVoid function

---

docs/Map.md
docs/Monoid.md
docs/Semigroup.md
src/Map.ts

I accidentally let a typo in before. Fixing the comment for `keys`.

Fix typo in Map's keys function comment: values -> keys

---

README.md

Fixes the API Reference link to point to the new docs @ https://gcanti.github.io/fp-ts

Fix link to new API Reference docs

---

docs/modules/Apply.ts.md
src/Apply.ts

This PR adds a couple of overloads to allow passing an increased number of arguments to `sequenceT` (up to 7 instead of just 5).
I had some problem running `npm test` in the repo (the `npm run prettier` command fails for some reason which I couldn't figure out) but the tests all pass.

Add overloads to sequenceT to allow more arguments (up to 7)

---

docs/_config.yml
docs/_sass/custom/custom.scss

The default purple color used by the documentation theme bothers me a bit as fp-ts always had more of a blue feel to me.
The purple combined with the blue fp-ts logo bothered me enough to learn a bit about Jekyll and to create this PR.
I have adjusted the link and button colors using the fp-ts logo as a guide. To me this gives the documentation a vastly more coherent look.
There is one small problem though. The current version of the theme is broken with regards to customisation. This forced me into switching to a forked version of the theme. 
There exists a PR attempting to solve the issue pmarsceill/just-the-docs#97
So I'm thinking that this PR, if accepted, should probably not be merged until the above is fixed and we can use the official theme again.
Anyway I though I'll leave this PR …

Adjust the documentation colors

---

docs/modules/function.ts.md
src/function.ts

This is a feature request to add new alias for Function.
`Function<A,B>` accepts functions has arguments which is any length. `A` is a tuple of arguments type such as `[number, number]` and `B` is the return type such as `number`.
```typescript
const add: Function<[number, number], number> = (a, b) => a+b;
``` 
Futhermore, `Function` which has no type arguments is equal to `(...args: any[])=>any`.

Add new Function alias

---

.gitignore
README.md
package.json
tsconfig.es6.json

This PR resolves #813 
Adds another step to the build script which outputs a bundle into `/es6` using es6 module syntax. Users can optionally switch to importing from `fp-ts/es6/*` rather than `fp-ts/lib/*` in order to make use of tree-shaking.

Add es6 module step to build for tree-shaking support

---

docs/modules/Zipper.ts.md
src/Zipper.ts
test/Zipper.ts

This PR adds a function which create a `Zipper` from a `NonEmptyArray2v`.

Create Zipper function fromNonEmptyArray2v.

---

perf/native-vs-task-taskEither-vs-readerTaskEither.ts

@sledorze I was trying to get an idea of how much we are loosing by stacking monads and the result is surprising (at least for `TaskEither`), is the benchmark code flawed?
TaskEither x 1,507,865 ops/sec ±5.95% (57 runs sampled)
native x 1,153,964 ops/sec ±7.83% (57 runs sampled)
ReaderTaskEither x 405,216 ops/sec ±9.67% (26 runs sampled)
Fastest is **TaskEither**

Perf: add monad stack comparison benchmark

---

src/IO.ts

This PR adds beginner friendly code examples from #531 to IO Overview. Some of the sequence code examples might be useful for other types with slight modifications. However, I think we may need to repeat some of the more generic concepts in several parts of the documentation since people who are reading the documentation do not know where to look for the more generic documentation. They only know that they are right now working with `IO` and wondering how to deal with problems that arise from dealing with `IO`. The fact that there are other types like `Either` which are similar and support similar operations do not help them at that point. However, as they are reading through several pages of documentation they will hopefully notice the pattern between the two.

Add code examples to IO Overview

---

src/fluent.ts

If they are not exported, writing a line of code in your app like this:
```ts
export const fluentEither = fluent(either);
```
gives:
`Exported variable 'fluentEither' has or is using name 'Fluent2' from external module "/Users/src/app/node_modules/fp-ts/lib/fluent" but cannot be named.ts(4023)`

export the Fluent types

---

src/Monoid.ts

Problem:
```ts
import { fold, getEndomorphismMonoid } from 'fp-ts/lib/Monoid';
fold(getEndomorphismMonoid<number>())([a => a + 1, b => b * 2])(3)
```
throws an error
```
Uncaught TypeError: fns[i].call is not a function
at function.js:100
```
The problem is that `compose` gets called with 4 instead of 2 parameters. The additional two are `index` and `array` from the `reduce` function call.

Use explicit concat function for getEndomorphismMonoid

---

CHANGELOG.md
docs/modules/NonEmptyArray2v.ts.md
package.json
src/NonEmptyArray2v.ts
src/Record.ts
test/NonEmptyArray2v.ts

- **Polish**
- fix `NonEmptyArray` definition
- **Deprecation**
- deprecate `NonEmptyArray.make` in favour of `cons`

version 1.18.2

---

docs/modules/Array.ts.md
dtslint/ts3.1/index.ts
src/Array.ts
src/NonEmptyArray2v.ts
test/Array.ts

This PR changes the signature of the chop function to use `NonEmptyArray` as the type of the argument of the function passed as second argument because it's called always with a `NonEmptyArray`.
This PR also adds a simple type predicate to allow narrowing down an `Array` to a `NonEmptyArray`, which is useful for while loop, if-else or ternary operator, but also in all functions where a type predicate has to be provided.

Makes array chop easier to use

---

docs/introduction/ecosystem.md

I've created a [module with Kleisli arrows](https://github.com/YBogomolov/kleisli-ts), a port of Scala ZIO's `KleisliIO` by John A. De Goes. It uses MonadThrow and Bifunctor instances from fp-ts.

Add kleisli-ts module

---

docs/introduction/upgrade-to-v2.md

I started an upgrade guide for the v1 -> v2 transition, I hope it helps. Depending on how many questions are asked, this guide might evolve.
I hoped to do this earlier, but time is sparse at the moment, sigh …

Add an upgrade guide for v2

---

docs/introduction/ecosystem.md

I have created bindings for [IxJS](https://github.com/ReactiveX/IxJS) and would like to add my lib to the ecosystems page.
Btw IxJS is a great library when you want FP style nodejs streams with back pressure handling.

fp-ts-ixjs to ecosystem added

---

docs/modules/IO.ts.md
src/IO.ts

Thanks for the awesome library! The part on sequencing IOs is outdated as `sequence_` is not exported from `Foldable` anymore, so I replaced that with `array.sequence(io)`. I'm not sure if this was the correct way to do replace the example as `array.sequence(io)` also allows accessing the results, and the current docs are talking about discarding the results. To an FP newbie like me an example that combines the actions without dropping the results seems a bit more useful (one can always discard the results with `io.map(() => (})`).

Fix outdated documentation in IO.ts

---

docs/recipes/ramda.md

I just noticed it's linking to the 1.x branch so not sure if this change makes sense, but it's missing the trailing `.md`.

fix(ramda recipe): map link incorrect

---

docs/modules/IOEither.ts.md
docs/modules/TaskEither.ts.md
src/IOEither.ts
src/TaskEither.ts
test/IOEither.ts
test/TaskEither.ts

A few doubts:
- ~I'm not sure the tests add any value (if yes, I will add them for other functions too)~ EDIT: left a single one just to obtain the necessary jest coverage
- ~I wanted to add `getFilterable` to `Either` but then stopped and just reused `getWitherable` in order to avoid duplicating part of the logic. If you feel it would add clarity, even at the cost of some duplication, I will split them~ EDIT: discussed offline with @gcanti , it should be already aligned to other similar constrained instances, where a new function has been added only if the constraint changes

add constrained Filterable instance to IOEither, TaskEither

---

src/Apply.ts

Without this, sequenceT and sequenceS would not work with HKT4s, such as StateReaderTaskEither:
```ts
import { StateReaderTaskEither, stateReaderTaskEither } from './../src/StateReaderTaskEither';
import { sequenceS, sequenceT } from '../src/Apply'
const foo: StateReaderTaskEither<number, {}, string, number> = stateReaderTaskEither.of(1)
const bar: StateReaderTaskEither<number, {}, string, string> = stateReaderTaskEither.of("bar")
sequenceT(stateReaderTaskEither)(foo, bar)
sequenceS(stateReaderTaskEither)({
a: foo,
b: bar
})
```
- If you've fixed a bug or added code that …

Adding sequenceT and sequenceS overload signatures for Kind4, fixes #969

---

docs/recipes/purescript.md

Typo in `Functor2` definition in PureScript recipes doc. This doesn't appear to be generated from source; the `L` is not in the other docs https://github.com/gcanti/fp-ts/blob/7bda18e34eed996a08afdd6a0a61025087f99593/docs/modules/Functor.ts.md#functor2-interface

Change `L` to `E`

---

docs/introduction/code-conventions.md

Looks like this commit changed a lot of the type variable names
https://github.com/gcanti/fp-ts/commit/7bda18e34eed996a08afdd6a0a61025087f99593#diff-dccd8b3f1d6a82046698bcefd53a06a7
There were a few that got overlooked

Update type variables in documentation

---

docs/modules/ReaderT.ts.md
docs/modules/boolean.ts.md
src/ReaderT.ts

This PR allows to define `ReaderThese` using `getReaderM` as helper
```ts
import { getMonoid } from 'fp-ts/lib/Array'
import { getReaderM } from 'fp-ts/lib/ReaderT'
import { getMonad } from 'fp-ts/lib/These'
const monadThese = getMonad(getMonoid<string>())
export const M = getReaderM(monadThese) // <= this errored out
```

add ReaderM2C

---

docs/modules/OptionT.ts.md
docs/modules/boolean.ts.md
src/OptionT.ts

This PR allows to define `TupleOption` using `getOptionM` as helper
```ts
import { getMonoid } from 'fp-ts/lib/Array'
import { Option } from 'fp-ts/lib/Option'
import { getOptionM } from 'fp-ts/lib/OptionT'
import { getMonad } from 'fp-ts/lib/Tuple'
export type TupleOption<E, A> = [Option<A>, E]
export const M = getOptionM(getMonad(getMonoid<string>())) // <= this errored out
```

add OptionM2C

---

src/Ord.ts
test/Ord.ts

Following https://github.com/gcanti/fp-ts/pull/1046, I think it would be semantically consistent to add a `Monoid<Ord>` instance, with `empty` returning an `Ord` instance which always considers compared elements equal (Js now guarantees to not to change order of elements in such a case - "no sorting applied" - sorting in js is now guaranteed to be stable). Besides consistency with `sortBy` implementation which can now take empty array of ords as input (and then performs "no sorting at all" - data remains untouched) it honestly... makes `sortBy` unnecessary (because we can now always build a specific `Ord` first, using `fold`), which leaves us with nice, terse and consistent interface for sorting, made of one function only - `sort` itself.

Add `getMonoid` for Ord

---

docs/introduction/ecosystem.md

I've created a `fetcher-ts` module – a type-safe HTTP client with `io-ts` validation support and ability to transform into a `TaskEither`. I would like to see it added to the ecosystem.

Add fetcher-ts to ecosystem

---

docs/modules/MonadIO.ts.md
docs/modules/MonadTask.ts.md
docs/modules/StateReaderTaskEither.ts.md
src/MonadIO.ts
src/MonadTask.ts
src/StateReaderTaskEither.ts

`MonadTask4` and all upper dependencies added. `MonadTask4` was then added to `StateReaderTaskEither`. I also added the missing exports for `fromPredicate` and `filterOrElse`.

MonadTask4 added

---

docs/modules/TaskEither.ts.md
src/TaskEither.ts
test/TaskEither.ts

This PR adds `tryCatchK`, which converts a function returning a `Promise` to one returning a `TaskEither`.

Add tryCatchK in TaskEither module

---

docs/ecosystem.md

I've ported Haskell library `alga` to TypeScript, and used `fp-ts` for HKT to provide Monad & Alternative instances. I would be happy to see it as a part of awesome `fp-ts` ecosystem.

Add alga-ts library

---

docs/learning-resources.md
src/IORef.ts
test/IORef.ts

I made all attributes `readonly` and solved a problem that occurs when you try to `pipe` the functions of an `IORef` instance. The problem is that the `this` context gets lost when using the methods directly.
```ts
const ref = new IORef('hello')
pipe('world', ref.write)() // This would throw: Uncaught TypeError: Cannot set property 'value' of undefined
```

IORef this binding problems solved

---

src/IOEither.ts
src/ReaderEither.ts
src/ReaderTaskEither.ts
src/TaskEither.ts

Detected using typescript@next, which has an error for this case. (microsoft/TypeScript#37063)

Remove redundant URI in spreads

---

package-lock.json

This PR contains changes caused by running `npm audit fix` on latest `Node 12.16.1 LTS`.
Also contains `optional` annotations for some packages in lockfile.
Note: this is not a breaking change (no `--force` flag).

build(npm): npm audit fix

---

docs/guides/code-conventions.md

I was a bit confused when reading the documentation regarding the meaning of `C` in type classes names such as [`Functor2C`](https://github.com/gcanti/fp-ts/blob/21461b8c6de99620f3b127f4fbfbca915f1a6059/src/Functor.ts#L43) or [`Applicative2C`](https://github.com/gcanti/fp-ts/blob/21461b8c6de99620f3b127f4fbfbca915f1a6059/src/Applicative.ts#L61).
If I understood it correctly, the `C` doesn't mean _curried_, but rather _constrained_, e.g. the "left" parameter of the [`Writer monad`](https://github.com/gcanti/fp-ts/blob/21461b8c6de99620f3b127f4fbfbca915f1a6059/src/Writer.ts#L96) must be an instance of Monoid.
Unless I misunderstood it? 🤔

Fix meaning of C in code conventions docs

---

docs/learning-resources.md

Not sure if it belongs here though, since `Do` is in `fp-ts-contrib`, but I guess it's a good idea to have the resources in one place.

Add article about Do by Paul Gray

---

src/StateT.ts

Add missing `StateM2C` and `StateM3C` definitions, as well as their usage in `getStateM()`.
I added `Since @2.5.4` in the jsdoc, but i'm not sure what is the value that actually need to go there. Maybe it should be `@2.6.0`? 
As a side note, it seems that it is possible to type `state` in `src/State.ts` on line 88, as `StateM1<IdentityURI>`. This would allow state to be passed in functions which require `StateM` instances. Should that be added?

Add missing StateM2C and StateM3C

---

CHANGELOG.md
dtslint/ts3.5/Either.ts
dtslint/ts3.5/IOEither.ts
dtslint/ts3.5/Option.ts
dtslint/ts3.5/Reader.ts
dtslint/ts3.5/ReaderEither.ts
dtslint/ts3.5/ReaderTaskEither.ts
dtslint/ts3.5/StateReaderTaskEither.ts
dtslint/ts3.5/TaskEither.ts
src/Either.ts
src/IOEither.ts
src/Option.ts
src/Reader.ts
src/ReaderEither.ts
src/ReaderTaskEither.ts
src/StateReaderTaskEither.ts
src/TaskEither.ts

- **New Feature**
- `Either`
- add `getOrElseW`
- add `chainW`
- `IOEither`
- add `getOrElseW`
- add `chainW`
- `Option`
- add `getOrElseW`
- `Reader`
- add `chainW`
- `ReaderEither`
- add `getOrElseW`
- add `chainW`
- `ReaderTaskEither`
- add `getOrElseW`
- add `chainW`
- `StateReaderTaskEither`
- add `chainW`
- `TaskEither`
- add `getOrElseW`
- add `chainW`

add W variants, closes #904

---

src/IO.ts

In the example:
```ts
pipe(
fromNullable(input),
fold(log('Received null'), value => log(`Received ${value}`)),
);
```
the left side of the fold needs to return a thunk, otherwise the resulf of the pipe isn't callable.

Fix IO example

---

CHANGELOG.md
perf/Apply/sequenceS.ts
perf/Apply/sequenceT.ts
src/Apply.ts
test/Apply.ts

**Before**
`sequenceT`
```
sequenceT (1) x 3,038,314 ops/sec ±1.06% (86 runs sampled)
sequenceT (2) x 1,486,717 ops/sec ±1.80% (86 runs sampled)
sequenceT (3) x 1,033,153 ops/sec ±0.79% (85 runs sampled)
sequenceT (4) x 799,994 ops/sec ±0.81% (87 runs sampled)
sequenceT (5) x 625,985 ops/sec ±0.80% (90 runs sampled)
```
`sequenceS`
```
sequenceS (1) x 2,723,960 ops/sec ±0.78% (86 runs sampled)
sequenceS (2) x 1,266,164 ops/sec ±0.74% (89 runs sampled)
sequenceS (3) x 809,389 ops/sec ±1.03% (89 runs sampled)
sequenceS (4) x 638,330 ops/sec ±1.43% (86 runs sampled)
sequenceS (5) x 522,986 ops/sec ±1.21% (89 runs sampled)
```
**After**
`sequenceT`
```
sequenceT (1) x 15,737,986 ops/sec ±0.71% (88 runs sampled)
sequenceT (2) x 8,389,840 ops/sec ±0.65% (86 runs sampled)
sequenceT (3) x …
```

improve performance of sequenceT and sequenceS, fix #1255

---

docs/modules/Foldable.ts.md
src/Foldable.ts
test/Foldable.ts

👋 
I saw an open PR, "Added Option.toArray" (https://github.com/gcanti/fp-ts/pull/1155), and noticed @gcanti recommended instead adding `toArray` to Foldable.
I went ahead and added it. However, I'm not 100% sure about the implementation.
In 2.x+, `Array` is deprecated in favor of `ReadOnlyArray`, but the original implementation of `toArray` uses a combination of `reduce` and `arr.push`.
**Possible problem**: `.push` does not exist on `ReadOnlyArray` since it mutates the array in place. This method is probably faster, but it might not desirable in the 2.x+ world.
Would it make sense to add another instance, `toReadOnlyArray`?
**Update**: I went ahead and also added a `toReadOnlyArray` instance. There appeared to be some prior art in the Map, Set, and Record modules.
I'm open to feedback …

Foldable: add `toArray`

---

test/Ord.ts

Fixing test body to reflect what the test is describing.

ordBoolean test should test boolean compare

---

src/TaskEither.ts

Thanks for this excellent and remarkably complete library!
This adds the type signature of `TaskEither` to the introductory
paragraph on the `TaskEither` page in a way that aligns with the `Task`
docs, which also have the signature at the top.
I'm opening this because when I first used `TaskEither`, I hadn't used
`Task` yet, either, and I didn't realize how to get the promise out of
it. I started out by looking for some kind of destructor method rather
than thinking it was callable. It was only when I looked at the `Task`
documentation that I realized it should be callable.
It's possible that if the top of the file had directed me that it was
an extension of `Task`, I might have figured it out sooner. I should
have thought to look down around line 860, where the existing docs
describe the …

doc: add type signature for `TaskEither` in module intro

---

test/State.ts

There's an edge case where testing the `State` monad with `Do` notation where the original state is overwritten by the chained.
By inputting the state as a real value and not `undefined`, we ensure that the input state is passed through and not overwritten by undefined in `_.of("b")`, where the state is initialized as undefined.
I discovered this when creating tests for `Do` notation for `fp-ts-rxjs/StateReaderObservableEither`. I wrote this test because I thought this was a bug with it's implementation because I copied the code from `fp-ts`, but it seems to be a different cause.
The test passes, meaning it's working as intended.

test(state): check for original state instead of undefined

---

docs/modules/NonEmptyArray.ts.md
docs/modules/ReadonlyNonEmptyArray.ts.md
src/NonEmptyArray.ts
src/ReadonlyNonEmptyArray.ts
test/NonEmptyArray.ts
test/ReadonlyNonEmptyArray.ts

Added the functions under a new `destructor` category.
`Array` and `RA` versions could also be added, with optional results, if needed.

NEA, RNEA: Add `uncons`, `unsnoc` destructors

---

src/IOEither.ts
src/ReaderTaskEither.ts
src/Task.ts
src/TaskEither.ts

More of the same (#1368)
@gcanti WDYT about using a tool which adds these automatically? Something like https://github.com/Andarist/babel-plugin-annotate-pure-calls.

Add more `/*#__PURE__*/` comments to improve tree shaking

---

docs/modules/Either.ts.md
docs/modules/IO.ts.md
docs/modules/Option.ts.md
docs/modules/Reader.ts.md
docs/modules/Task.ts.md
docs/modules/TaskEither.ts.md
src/Either.ts
src/IO.ts
src/Option.ts
src/Reader.ts
src/Task.ts
src/TaskEither.ts

Fix two small typos
`this function have` -> `this function has`
`and perform better` -> `and performs better`

Fix documentation typos

---

docs/modules/Array.ts.md
docs/modules/ReadonlyArray.ts.md
src/Array.ts
src/ReadonlyArray.ts

Given scanLeft/Right, unlike reduce, always returns an array that has at least one element (the seed),
it makes sense to me to be more specific about the result.
What do you think? Are there any unintended consequences I'm missing here?

Array, ReadonlyArray: change scanLeft & scanRight to return NonEmpty

---

docs/ecosystem.md

Since the matechs library was renamed to effect-ts it's probably a good idea to update links in the ecosystem.md file

Remove matechs-effect from ecosystem.md

---

CHANGELOG.md
docs/modules/Array.ts.md
docs/modules/Map.ts.md
docs/modules/NonEmptyArray.ts.md
docs/modules/ReadonlyArray.ts.md
docs/modules/ReadonlyNonEmptyArray.ts.md
docs/modules/Record.ts.md
docs/modules/Tree.ts.md
package.json
src/Array.ts
src/Map.ts
src/NonEmptyArray.ts
src/ReadonlyArray.ts
src/ReadonlyMap.ts
src/ReadonlyNonEmptyArray.ts
src/ReadonlyRecord.ts
src/Record.ts
src/Tree.ts
test/Array.ts
test/Map.ts
test/NonEmptyArray.ts
test/ReadonlyArray.ts
test/ReadonlyMap.ts
test/ReadonlyNonEmptyArray.ts
test/ReadonlyRecord.ts
test/Record.ts

Related: https://github.com/gcanti/fp-ts/issues/1420

version 2.10.0 rc.4

---

docs/modules/Apply.ts.md
src/Apply.ts

Make the example slightly more declarative.
The current use of the `ternary operator` is equal to `String(x)` or `x.toString()`
Node repl session
```
> c = true
> (c ? 'true' : 'false') === String(c)
true
> c = false
> (c ? 'true' : 'false') === String(c)
true
```
Note: I changed the source example and ran `npm run docs`

update Apply example

---

docs/modules/NonEmptyArray.ts.md
docs/modules/ReadonlyNonEmptyArray.ts.md
src/NonEmptyArray.ts
src/ReadonlyNonEmptyArray.ts
test/NonEmptyArray.ts
test/ReadonlyNonEmptyArray.ts

**New Feature** (for v2.11)
NonEmptyArray/ReadonlyNonEmptyArray:
- added `matchLeft`
- added `matchRight`
- added `modifyHead`
- added `modifyLast`
These were added based on the discussion seen in https://github.com/gcanti/fp-ts/issues/1420

Non empty arr additions

---

docs/modules/Array.ts.md
src/Array.ts
test/Array.ts

New feature for `Array`:
- added `fromPredicate`
- added `fromOption`
closes #1437

Add fromPredicate & fromOption to Array

---

src/Array.ts
src/ReadonlyArray.ts
test/ReadonlyArray.ts

Addition of two implementations of chainRec (depth-first and breadth-first) for ReadonlyArray and Array.
In `ChainRec` instance by default the depth-first method is selected, but there is access to breadth-first via `BreadthFirstChainRec` instances.
As for the optimization of each of the two algorithms, breadth-first avoids initial array copy by having two loops that do the same thing. In depth-first I couldn't avoid copy of the initial array.

Array chain rec

---

docs/modules/function.ts.md
src/ReadonlyMap.ts
src/ReadonlyNonEmptyArray.ts
src/ReadonlyRecord.ts
src/function.ts

Backports `SK` from 3.0.0 to 2.11 based on the v2.11 roadmap https://github.com/gcanti/fp-ts/issues/1446

Backport SK

---

docs/modules/ReadonlyRecord.ts.md
docs/modules/Record.ts.md
dtslint/ts3.5/ReadonlyRecord.ts
dtslint/ts3.5/Record.ts
src/ReadonlyRecord.ts
src/Record.ts
test/ReadonlyRecord.ts
test/Record.ts

Backports `ReadonlyRecord` from 3.0.0 based on the 2.11 roadmap https://github.com/gcanti/fp-ts/issues/1446
I agree w/ the `Ord` idea outlined in the roadmap, but I can change if desired.
Notes:
- I used `Ord` constraints in `Record` as well, I can change it to use `Ord.trivial` if desired
- I wasn't sure why `ReadonlyRecord.wilt` and `ReadonlyRecord.wither` [use `Ord.trivial`  in 3.0.0](https://github.com/gcanti/fp-ts/blob/f7ae980afcab8f68d46b801f35462e644a64a65c/src/ReadonlyRecord.ts#L756), but I mirrored that - I'm not sure if that was correct
- I also added `Ord` instances to these, which were unspecified - we can use `Ord.trivial` instead if desired
- `traverse`
- `sequence`
- `getShow`
- typeclass instances (`Traversable` -> `getTraversable: (O: Ord<string>) => ...`)

Backport ReadonlyRecord & Record

---

src/Monoid.ts
src/ReadonlyRecord.ts
src/Semigroup.ts
src/Show.ts
src/internal.ts

Re. https://github.com/gcanti/fp-ts/issues/1249#issuecomment-820232156

Workaround issue with `hasOwnProperty`

---

docs/modules/ReaderTaskEither.ts.md
src/ReaderTaskEither.ts
test/ReaderTaskEither.ts

This P.R. adds:
- `ReaderTaskEither.fromReaderTaskK`
- `ReaderTaskEither.chainReaderTaskK`
- `ReaderTaskEither.chainReaderTaskKW`

Add ReaderTaskEither.fromReaderTaskK, ReaderTaskEither.chainReaderTaskK and ReaderTaskEither.chainReaderTaskKW

---

CHANGELOG.md
docs/modules/Either.ts.md
docs/modules/IOEither.ts.md
docs/modules/Reader.ts.md
docs/modules/ReaderEither.ts.md
docs/modules/ReaderTask.ts.md
docs/modules/ReaderTaskEither.ts.md
docs/modules/StateReaderTaskEither.ts.md
docs/modules/TaskEither.ts.md
src/Either.ts
src/IOEither.ts
src/Reader.ts
src/ReaderEither.ts
src/ReaderTask.ts
src/ReaderTaskEither.ts
src/StateReaderTaskEither.ts
src/TaskEither.ts
test/Either.ts
test/IOEither.ts
test/Reader.ts
test/ReaderEither.ts
test/ReaderTask.ts
test/ReaderTaskEither.ts
test/StateReaderTaskEither.ts
test/TaskEither.ts

Eg. for `Either`, allows:
```
function a(input: E.Either<E1, E.Either<E2, A>>): E.Either<E1 | E2, A> {
return E.flattenW(input)
}
```
instead of:
```
function a(input: E.Either<E1, E.Either<E2, A>>): E.Either<E1 | E2, A> {
return pipe(input, E.chainW(id => id))
}
```
i.e. allows the Left type to widen.

Add flattenW (less strict version of flatten) to all types that also have chainW

---

src/Functor.ts

Adds missing overloads to `Functor.map` for Kind(2/3/4) in the 3.0.0 branch

Additional 3.x Functor.map overloads

---

src/Reader.ts

Name the Reader variable in the promap type signature `fea` instead of `fbc`.

fix: Name Reader variable correct in promap type signature

---

docs/ecosystem.md

Adds [spectacles-ts](https://github.com/anthonyjoeseph/spectacles-ts/) to the fp-ts ecosystem page
It's a simple, syntactically-sugary facade built on top of monocle-ts that autocompletes possible combinators
I think this library could be valuable as a way to get beginners hooked on fp-ts - it's simple to use, has a pretty universal use-case, and heavily features 'pipeable' syntax and the `Option` type
(Ofc please feel free to close this PR - I wasn't sure the best place to have this discussion and I'd be happy to relocate)

Add spectacles-ts to Ecosystem

---

src/function.ts
test/function.ts

V8 has a performance cliff when there's more than 10 case blocks in a switch
statement. This fix reduces the number of fast specialised case statements
to 9 + extra one for general case.
More details here: https://groups.google.com/g/v8-users/c/_Add2xOVmfU/m/IQHh2IAVBAAJ
Fixes: https://github.com/gcanti/fp-ts/issues/1507

pipe: fix v8 performance cliff for >10 case stmts

---

docs/modules/Option.ts.md
src/Option.ts

add missing NonNullable
Why:
```ts
type A = {
k?: Array<'hello' | 'world'> | undefined
}
function program<K extends keyof A>(
k: K,
fa: O.Option<A>
): NonNullable<A[K]>[number] | undefined {
// Type 'unknown' is not assignable to type 'NonNullable<A[K]>[number] | undefined'.
//  Type 'unknown' is not assignable to type 'NonNullable<A[K]>[number]'.
//    Type 'unknown' is not assignable to type 'string'.ts(2322)
// |
return pipe(
fa,
O.chainNullableK((a) => a[k]),
O.chain(A.head),
O.toUndefined
)
}
```
This code does not compile. The expected result should be
```ts
function program<"k">(k: "k", fa: O.Option<A>): "hello" | "world" | undefined
```

fix chainNullableK from option

---

src/Task.ts
test/Task.ts

We can improve the stack safety of tasks by forcing suspension of otherwise sync closure calls. 
The suspension mechanism used to trampoline a thunk f is `Promise.resolve().then(f)` that uses microtasks (higher priority compared to setTimeout's)
Effectively closes #1177 for async tasks.

Stack safety for Task via microtasks suspension

---

docs/modules/StateT.ts.md
src/StateT.ts

StateT3 is in the utils section of the documentation page at present, which I presume is due to it not having a category marker.

`StateT`: Add missing category marker to `StateT3`

---

src/ReaderTaskEither.ts
test/ReaderTaskEither.ts

Add chainFirstEitherK(W) in ReaderTaskEither module

---

docs/modules/Array.ts.md
src/Array.ts

Adding descriptions and examples for several functions of the Array module.
My aim is to make the awesome `fp-ts` library a bit more accessible to users and to beginners in particular.
No changes have been done to the actual code.
Thanks in advance for every feedback and input for additional improvement.
Filippo

Improving Array module documentation

---

docs/modules/Array.ts.md
docs/modules/ReadonlyArray.ts.md
docs/modules/ReadonlyRecord.ts.md
docs/modules/ReadonlySet.ts.md
docs/modules/Record.ts.md
docs/modules/Set.ts.md
src/Array.ts
src/ReadonlyArray.ts
src/ReadonlyRecord.ts
src/ReadonlySet.ts
src/Record.ts
src/Set.ts

I have added `Refinement` overloads to the `every` function of `ReadonlyArray`,  `ReadonlyRecord`, `ReadonlySet` and their mutable counterparts.
Example
```ts
import { every } from 'fp-ts/ReadonlyArray'
import { isNumber } from 'fp-ts/number'
declare const as: ReadonlyArray<string | number>
every(isNumber)(as) // ReadonlyArray<number>
```

Refinement overload added to 'every' functions

---

docs/modules/TaskEither.ts.md
docs/modules/TaskOption.ts.md
src/TaskEither.ts
src/TaskOption.ts
test/TaskEither.ts
test/TaskOption.ts

This reopens and updates #1001 to allow `f` in `TaskEither` and `TaskOption`'s `tryCatch`/`tryCatchK` to throw an error (as opposed to only returning a resolved/rejected promise).
Fixes #1672.

try/catch in tryCatch

---

docs/modules/IOEither.ts.md
docs/modules/TaskEither.ts.md
dtslint/ts3.5/IOEither.ts
dtslint/ts3.5/TaskEither.ts
src/IOEither.ts
src/TaskEither.ts
test/IOEither.ts
test/TaskEither.ts

This adds `orElseFirstIOK` to `IOEither` and `TaskEither`, and `orElseFirstTaskK` to `TaskEither`, which are useful to help when logging (the left).
Refs https://github.com/gcanti/fp-ts/issues/1360#issuecomment-811972265

Add orElseFirstIOK and orElseFirstTaskK

---

src/IOEither.ts
src/ReaderTaskEither.ts
src/TaskEither.ts
test/IOEither.ts
test/ReaderTaskEither.ts
test/TaskEither.ts

Added `bracketW` functions.
Sadly, the `docs` script doesn't work to me (this is the issue #1626) so I can't generate docs.

Added bracketW functions

---

docs/modules/EitherT.ts.md
docs/modules/TaskEither.ts.md
src/EitherT.ts
src/TaskEither.ts
test/TaskEither.ts

I noticed that both `Either` and `TaskOption` had implementations of `chainNullableK`, `fromNullable`, and `fromNullableK`, but `TaskEither` did not. This PR adds implementations of those three functions for `EitherT` and `TaskEither`.
This was quite rote, so if there's some secret sauce to how many overloads are present in, say, `OptionT` vs `EitherT`, I'd appreciate someone pointing it out.

Add nullable interop helpers for `EitherT` & `TaskEither`

---

docs/modules/Array.ts.md
docs/modules/NonEmptyArray.ts.md
docs/modules/ReadonlyArray.ts.md
docs/modules/ReadonlyNonEmptyArray.ts.md
src/Array.ts
src/NonEmptyArray.ts
src/ReadonlyArray.ts
src/ReadonlyNonEmptyArray.ts
test/Array.ts
test/NonEmptyArray.ts
test/ReadonlyArray.ts
test/ReadonlyNonEmptyArray.ts

Based on `intercalate` in PureScript's [`Data.Array`](https://pursuit.purescript.org/packages/purescript-arrays/6.0.1/docs/Data.Array#v:intercalate) and [`Data.Array.NonEmpty`](https://pursuit.purescript.org/packages/purescript-arrays/6.0.1/docs/Data.Array.NonEmpty#v:intercalate).

Add intercalate to arrays

---

src/ReadonlyRecord.ts
test/ReadonlyRecord.ts

fix(ReadonlyRecord): `traverse` clones objects in place instead of referencing and assigning to them.

---

docs/modules/ReadonlyRecord.ts.md
docs/modules/Record.ts.md
src/ReadonlyRecord.ts
src/Record.ts

This allows the usage for `Record#traverse` with `StateReaderTaskEither` or `hyper-ts/ReaderMiddleware`.

Applicative4 added to Record traverse

---

src/TaskEither.ts

if we wanted to chain a function which returns TaskOption in a TaskEither pipeline we would have to do
```typescript
import * as TE from 'fp-ts/TaskEither'
import * as TO from 'fp-ts/TaskOption'
declare const fooTaskEither: TE.TaskEither<'no', number>;
declare const getTaskOption: (x: number) => TO.TaskOption<boolean>;
const x = pipe(
fooTaskEither,
TE.chainW(TE.fromTaskOptionK(() => 'big no' as const)(getTaskOption)),
);
// x : TE.TaskEither<'big no' | 'no', boolean>
```
but I thought it would be a better idea if we could do this instead:
```typescript
const x = pipe(
fooTaskEither,
chainTaskOptionKW(() => 'big no' as const)(getTaskOption),
);
// x : TE.TaskEither<'big no' | 'no', boolean>
```

feat: add chainTaskOptionKW

---

src/Apply.ts

There are some overloads missing that I needed in in my projects, and figured we may as well add all the overloads for the functions.
Questions:
- What is preferred, A => B or A1 => A2? I prefer the latter because there's no good standard on letters after Q.
- Could we do A1 instead of A? I've been using vim search and replace and it's much easier when they all have numbers.

feat(Apply/ap): make total overloads `F: 0,1,2,2C,3,3C,4` to `G: 1,2,2C,3,3C,4`

---

docs/modules/IO.ts.md
docs/modules/IOEither.ts.md
docs/modules/IOOption.ts.md
src/IO.ts
src/IOEither.ts
src/IOOption.ts

Adds description to IOOption and references to IOOption to IO & IOEither.
The references are a repeated sentence for ease of understanding/searching, but I will happily re-write or re-format to lose repetition if preferred.

IOOption: add description

---

README.md

The `david-dm.org` website is down for 3 months, and the project `alanshaw/david` is not actively maintained anymore. The `david-dm.org` should be considered dead, thus badges should be removed from README.

docs: remove david-dm.org from README

---

docs/modules/function.ts.md
dtslint/ts4.1/function.ts
src/function.ts
test/function.ts

This is the follow-up to #1748 on v3, replacing the deprecation. (The commits there haven't been merged into the new branch yet, so this will create a conflict if it does.)

Flip the arguments of a curried function

---

docs/modules/Alternative.ts.md
src/Alternative.ts
test/Alternative.ts

This provides a way to lift a semigroup into a monoid via an alternative...
think of it like a generalised version of `Option`'s `getMonoid`, except it applies to any `Alternative`.
It also means any module without a specialised `getMonoid` function like `TaskOption` and `IOOption` also have a way to produce an amalgamation.
Hopefully this is useful and not a duplication of functionality.
Alternatively, should all Alternative-capable modules expose a `getMonoid` function?
I did debate adding a way to get an Alternative Semigroup from a Semigroup (and Alternative Monoid from a Monoid) but I realised this had the biggest bang for buck in utilising the capabilities of the underlying Alternative.
I am pretty sure the order of `() => F.alt(first, () => second))` is irrelevant given it's a …

Alternative: add getAlternativeMonoid

---

docs/modules/IOEither.ts.md
docs/modules/IOOption.ts.md
docs/modules/Option.ts.md
docs/modules/ReaderEither.ts.md
docs/modules/ReaderTaskEither.ts.md
docs/modules/StateReaderTaskEither.ts.md
docs/modules/TaskEither.ts.md
docs/modules/TaskOption.ts.md
src/FromEither.ts
src/IOEither.ts
src/IOOption.ts
src/Option.ts
src/ReaderEither.ts
src/ReaderTaskEither.ts
src/StateReaderTaskEither.ts
src/TaskEither.ts
src/TaskOption.ts
test/IOEither.ts
test/IOOption.ts
test/Option.ts
test/ReaderEither.ts
test/ReaderTaskEither.ts
test/StateReaderTaskEither.ts
test/TaskEither.ts
test/TaskOption.ts

feat: tapEither

---

docs/modules/IOEither.ts.md
docs/modules/IOOption.ts.md
docs/modules/ReaderIO.ts.md
docs/modules/ReaderTask.ts.md
docs/modules/ReaderTaskEither.ts.md
docs/modules/StateReaderTaskEither.ts.md
docs/modules/Task.ts.md
docs/modules/TaskEither.ts.md
docs/modules/TaskOption.ts.md
src/FromIO.ts
src/IOEither.ts
src/IOOption.ts
src/ReaderIO.ts
src/ReaderTask.ts
src/ReaderTaskEither.ts
src/StateReaderTaskEither.ts
src/Task.ts
src/TaskEither.ts
src/TaskOption.ts
test/IOEither.ts
test/IOOption.ts
test/ReaderIO.ts
test/ReaderTask.ts
test/ReaderTaskEither.ts
test/StateReaderTaskEither.ts
test/Task.ts
test/TaskEither.ts
test/TaskOption.ts

feat: tapIO

---

docs/modules/ReaderTask.ts.md
docs/modules/ReaderTaskEither.ts.md
docs/modules/StateReaderTaskEither.ts.md
docs/modules/TaskEither.ts.md
docs/modules/TaskOption.ts.md
src/FromTask.ts
src/ReaderTask.ts
src/ReaderTaskEither.ts
src/StateReaderTaskEither.ts
src/TaskEither.ts
src/TaskOption.ts
test/ReaderTask.ts
test/ReaderTaskEither.ts
test/StateReaderTaskEither.ts
test/TaskEither.ts
test/TaskOption.ts

feat: tapTask

---

docs/modules/ReaderTask.ts.md
docs/modules/ReaderTaskEither.ts.md
src/ReaderTask.ts
src/ReaderTaskEither.ts
test/ReaderTask.ts
test/ReaderTaskEither.ts

Add remaining tap*s

---

docs/modules/IOEither.ts.md
docs/modules/IOOption.ts.md
docs/modules/ReaderIO.ts.md
docs/modules/ReaderTask.ts.md
docs/modules/ReaderTaskEither.ts.md
docs/modules/StateReaderTaskEither.ts.md
docs/modules/Task.ts.md
docs/modules/TaskEither.ts.md
docs/modules/TaskOption.ts.md
src/IOEither.ts
src/IOOption.ts
src/ReaderIO.ts
src/ReaderTask.ts
src/ReaderTaskEither.ts
src/StateReaderTaskEither.ts
src/Task.ts
src/TaskEither.ts
src/TaskOption.ts
src/internal.ts
test/IOEither.ts
test/IOOption.ts
test/ReaderIO.ts
test/ReaderTask.ts
test/ReaderTaskEither.ts
test/StateReaderTaskEither.ts
test/Task.ts
test/TaskEither.ts
test/TaskOption.ts

- `flatMapReaderTask`
- `flatMapTaskEither`
- `flatMapIO` (+ internal-only new hkt type lambdas and instances)

Add ReaderTask, TaskEither and IO flatMaps

---

docs/modules/IOOption.ts.md
docs/modules/ReaderTaskEither.ts.md
docs/modules/StateReaderTaskEither.ts.md
docs/modules/TaskEither.ts.md
src/IOOption.ts
src/ReaderTaskEither.ts
src/StateReaderTaskEither.ts
src/TaskEither.ts
test/IOOption.ts
test/ReaderTaskEither.ts
test/StateReaderTaskEither.ts
test/TaskEither.ts

Add remaining `flatMap`s

---

docs/learning-resources.md

docs: update broken link

---

src/Either.ts
src/internal.ts

Currently there are some arrow functions that have /*#__PURE__*/
annotation before function call to identify that that function call is
side effect free.
However since this project is built to es5 target, which doesn't have
arrow functions support, the code is then translated into regular
function that loos something like this:
```
/** @internal */
export var flatMapNullable = function (F, M) {
/*#__PURE__*/ return dual(3, function (self, f, onNullable) {
return M.flatMap(self, liftNullable(F)(f, onNullable));
});
};
```
However this makes some built tools (Vite (which uses Rollup under the
hood) in our case) unhappy, and build produces a lot of warnings about
that __PURE__ annotation being in the wrong place.
Checking the Rollup docs [0], it seems that pure annotation should be
placed …

Fix __PURE__ annotation placement

---

docs/learning-resources.md

Hello! 👋
I've been working on an [fp-ts Tutorial series on YouTube](https://www.youtube.com/playlist?list=PLUMXrUa_EuePN94nJ2hAui5nWDj8RO3lH) for some time now, and I've made a good amount of videos that will help people getting started with fp-ts. In these videos, I try to cover fp-ts in a practical way that does not require prior knowledge of functional programming.
Given that many people are finding these videos helpful, I think it's a good idea to add a link to the series in the Learning Resources. Let me know what you think! Thank you! 🙏

docs: add fp-ts Tutorial series on YouTube to Learning Resources

---

src/Either.ts
test/Either.ts

Using Fast Check's `anything` arbitrary, I saw it generated an object with a `toString` property that wasn't a function which returned a string, leading to a 'TypeError: Cannot convert object to primitive value' failure.
This change returns an empty `Error` in those cases.

Don't fail when a value can't be converted to a primitive

---

package-lock.json
src/Array.ts
src/NonEmptyArray.ts
src/ReadonlyArray.ts
src/ReadonlyNonEmptyArray.ts

Fix: #1929 
Alternative to #1930 with a single commit for the change.

Fix: #1929 (use loop instead of <array-a>.push(...<array-b>)

---

src/Map.ts
src/ReadonlyMap.ts
src/ReadonlySet.ts
src/Set.ts

This updates the `fp-ts` build to be forwards compatible with microsoft/TypeScript#58243, which uses a stricter return type for built-in iterators under the new `strictBuiltinIteratorReturn` option, which is enabled by default when compiling with `strict`.

Support `strictBuiltinIteratorReturn`

---

docs/learning-resources.md

Correct the blog post section link, otherwise the original link will lead to a GitHub "Not Found" page.
Clicking the [link](https://ybogomolov.me/01-higher-kinded-types/)leads to a GitHub "Not Found" page.
https://gcanti.github.io/fp-ts/learning-resources/#community-blog-posts
The corrected link is [here](https://ybogomolov.me/01-higher-kinded-types), which should direct users to the correct page for the blog.

fix(doc): correct the blog section link, otherwise the original link will lead to a github not found page.
