- src/Traced.ts
- test/Traced.ts
i took a stab at adding Traced, based on Writer/Reader.
> feat: add Traced

- src/Either.ts
- test/Either.ts
> Either supports 'getOrElse'

- src/index.ts
Free is not exposed in `index.ts`.
> exposed Free

- docs/Free.md
The current docs are written from the perspective of the library's author.
This PR is more user friendly and assumes the audience is a developer interested in using the library.
> improved docs

- src/Apply.ts
- test/Apply.ts
> add applyFirst and applySecond to Apply

- src/Apply.ts
- src/Either.ts
- test/Apply.ts
- test/Either.ts
I've based the additional tests from results of Purescript implementations and fixed the code accordingly.
> fix errors in Either 'app' and Apply 'applyFirst'

- src/Monoidal.ts
- src/Tuple.ts
- test/Monoidal.ts
- test/Task.ts
```purescript
class Functor f => Monoidal f where
unit :: f () 
mult :: f a -> f b -> f (a,b)
```
> add Monoidal type class (strong lax monoidal functor)

- README.md
- src/Store.ts
Hi, I'm trying to implement the Store comonad (#100), but I guess I need to `extends` FantasyComonad and StaticComonad? Also what to do with `F extends HKTS`?
Thanks,
rilut
> Add Store comonad

- examples/EitherOption.ts
- examples/ReaderOption.ts
- examples/TaskEither.ts
- examples/TaskOption.ts
- src/Array.ts
- src/Id.ts
- src/NonEmptyArray.ts
- src/Reader.ts
- src/ReaderT.ts
- src/State.ts
- src/StateT.ts
- src/index.ts
- test/Array.ts
- test/NonEmptyArray.ts
- test/OptionT.ts
- test/ReaderT.ts
- test/State.ts
- test/StateT.ts
This seems a nice refactoring: I got `Reader` and `State` monads derived by respectively `ReaderT` and `StateT` (applying the `Id` monad)
> StateT and ReaderT

- src/Array.ts
- src/Const.ts
- src/Dictionary.ts
- src/Either.ts
- src/IO.ts
- src/Id.ts
- src/Identity.ts
- src/NonEmptyArray.ts
- src/Option.ts
- src/Reader.ts
- src/State.ts
- src/Store.ts
- src/Task.ts
- src/Traced.ts
- src/Tuple.ts
- src/Validation.ts
- src/Writer.ts
> Change proofs of implementation

- .vscode/settings.json
- src/Array.ts
- src/Either.ts
- src/Filterable.ts
- src/Option.ts
- src/Ring.ts
- src/Witherable.ts
- src/index.ts
- test/Filterable.ts
- test/Witherable.ts
> Add Witherable, closes #125

- src/HKT.ts
> Added bottom to HKTS

- src/Option.ts
- test/Option.ts
- contains
- isEmpty
- isDefined
- nonEmpty
- forEach
- exists
- orEmpty
see also issue https://github.com/gcanti/fp-ts/issues/183
> add the following member methods in Some / None classes :

- src/Array.ts
- test/Array.ts
- test/Monoid.ts
@raveclassic not sure about `fold` and `slice` though, I feel like they shouldn't be curried
> FR: migrate to curried // Array

- examples/TaskEither.ts
- src/ChainRec.ts
- src/Either.ts
- src/EitherT.ts
- test/Either.ts
- Chain was already ok
- the curried version of ChainRec.tailRec raises some type inference issues, keeping as is for now
> Chain, ChainRec, Either, EitherT

- package.json
- src/function.ts
- test/function.ts
@raveclassic apparently I forgot this module
> FR: migrate to curried // function

- src/Monoidal.ts
- src/function.ts
- test/function.ts
> add apply / applyFlipped

- examples/Moore.ts
- test/Moore.ts
This is not meant to be merged, it's just as exercise, a translation of this tweet by drboolean https://twitter.com/drboolean/status/898634041129279488
> add Moore machine

- examples/mtl.ts
This is an attempt to provide an example of a MTL-like programming style. It's adapted from Scala https://tech.iheart.com/why-fp-its-the-composition-f585d17b01d3 (nice blog post on functional programming btw)
The point is write code against interfaces and then provide possibly multiple implementations (test, production, etc..)
> In imperative programming, a great portion of the application code is repetitive effect handling in compositions, which is cumbersom, error prone, and very effect specific. This makes our application unecessarily complex, obscure and rigid to effects. Functional programming, powered by category theory, provides ways to compose components with effects in a concise and effect agnostic way.
> add MTL-like example

- src/Option.ts
> Add `toUndefined` to the Option type

- src/Task.ts
Fixes https://github.com/gcanti/fp-ts/issues/179
> Prefer `{}` to `any` type in Task

- src/Array.ts
- test/Array.ts
Thank you for this very helpful library!
I have added some functions I thought would have been useful when I first picked it up.
> Extra array functions

- src/Option.ts
- test/Option.ts
> add Option#filter

- src/Foldable.js.flow
- src/Foldable.ts
- test/Foldable.ts
- minimum
- maximum
- sum
- product
- foldM
- oneOf
- elem
- find
> add some Foldable functions

- docs/api/md/Option.md
- package-lock.json
- src/Option.ts
added api documentation for map.
> Option: documentation on map

- src/EitherT.ts
- src/TaskEither.ts
- test/TaskEither.ts
This PR makes taskEither an instance of BiFunctor.
> Make taskEither an instance of BiFunctor

- examples/TheseOption.ts
- src/Applicative.ts
- src/Functor.ts
- src/OptionT.ts
- typings-checker/index.ts
@pbadenski could you please review this PR?
> New Feature: add support for Monad2C and Monad3C to OptionT, closes #379

- src/BooleanAlgebra.ts
- src/BoundedDistributiveLattice.ts
- src/BoundedJoinSemilattice.ts
- src/BoundedLattice.ts
- src/BoundedMeetSemilattice.ts
- src/DistributiveLattice.ts
- src/HeytingAlgebra.ts
- src/JoinSemilattice.ts
- src/Lattice.ts
- src/MeetSemilattice.ts
- src/index.ts
@rklaehn could you please review?
> New Feature: add Lattice typeclass hierarchy, closes #412

- docs/api/md/IOEither.md
- docs/api/md/State.md
- docs/api/md/index.md
- src/IOEither.ts
- test/IOEither.ts
See https://github.com/gcanti/fp-ts/issues/433
I pretty much just `s/Task/IO/` across `TaskEither.ts` 😅
> New Feature: IOEither

- src/NonEmptyArray.ts
- test/NonEmptyArray.ts
adds `NonEmptyArray.prototype.sort`
> feature: add NonEmptyArray.prototype.sort

- src/ReaderTaskEither.ts
- src/index.ts
- test/ReaderTaskEither.ts
- typings-checker/index.ts
see https://github.com/gcanti/fp-ts/issues/446
> refactor: move ReaderTaskEither from examples into src

- src/Bifunctor.ts
- src/ReaderTaskEither.ts
- src/Task.ts
- src/TaskEither.ts
- test/ReaderTaskEither.ts
> ReaderTaskEither: add orElse, alt, bimap

- src/NonEmptyArray.ts
- test/NonEmptyArray.ts
adds safe reverse to NonEmptyArray
> feature: NonEmptyArray // add reverse

- src/TaskEither.ts
- typings-checker/index.ts
@dmechas I have also added a type-level test
> Bug Fix: fix TaskEither.taskify typings

- src/Either.ts
- test/Either.ts
@leemhenson @raveclassic do you have anything you want to add? Otherwise I'm going to release 1.6 after merging this
> Either: add functions based on refinements

- docs/BoundedJoinSemilattice.md
- docs/BoundedMeetSemilattice.md
- docs/HeytingAlgebra.md
- docs/JoinSemilattice.md
- docs/MeetSemilattice.md
- src/BoundedJoinSemilattice.ts
- src/BoundedMeetSemilattice.ts
- src/HeytingAlgebra.ts
- src/JoinSemilattice.ts
- src/MeetSemilattice.ts
- BoundedJoinSemilattice
- BoundedMeetSemilattice
- HeytingAlgebra
- JoinSemilattice
- MeetSemilattice
> Bug Fix: add missing readonly modifiers

- src/Array.ts
- test/Array.ts
Add foldr and foldrL function for Array, see the issue #469
> added foldr and foldrL

- src/Compactable.ts
- src/Either.ts
- src/index.ts
- test/Compactable.ts
First part of https://github.com/gcanti/fp-ts/pull/485
Adds `Compactable` typeclass, default imeplementations of `compact` and `separate` and tests
> feature: Compactable

- docs-generator/code2comment.html
- docs-generator/domain.ts
- docs-generator/main.ts
- docs-generator/markdown.ts
- docs-generator/parser.ts
- docs/Validation.md
- src/Validation.ts
+ applicative validation example
>  Docs: add support for @example tag to data

- README.md
- examples/Reader.ts
Hello!
I put together this example whilst trying to get a feel for how Reader monad works in this library, and thought it might be helpful to others as the other Reader examples are a bit more complicated.
Thanks everybody for their work on this library btw!
> Very basic Reader example

- src/TaskEither.ts
- test/TaskEither.ts
The added functions are a combination of the Monoid definitions from `Task` and `Either`.
> Make TaskEither a Monoid

- test/function.ts
Add `not` test case in `function.ts`
> Add `not` test case

- docs/TaskEither.md
- src/TaskEither.ts
- test/TaskEither.ts
Fix https://github.com/gcanti/fp-ts/issues/583
> New Feature: add TaskEither.prototype.foldM

- README.md
> add fp-ts-most to bindings

- package-lock.json
- package.json
- src/Array.ts
- src/NonEmptyArray.ts
- test/IOEither.ts
- test/NonEmptyArray.ts
- tslint.json
add index, findFirst, findLast, findIndex, findLastIndex, insertAt, updateAt, filter to nonEmptyArray and homogeneise findLastIndex with Array for refinement
> NonEmptyArray enhancement (fixes #627)

- src/Reader.ts
- src/Semigroupoid.ts
- src/Strong.ts
- src/index.ts
- test/Reader.ts
- test/Strong.ts
- add Category instance to Reader
- add Strong instance to Reader
> New Feature: add Strong type class

- src/Array.ts
- src/NonEmptyArray.ts
- src/StrMap.ts
- src/TraversableWithIndex.ts
- src/index.ts
- test/Array.ts
- test/NonEmptyArray.ts
plus instances for
- Array
- NonEmptyArray
- StrMap
> add TraversableWithIndex type class, closes #618

- src/Array.ts
- test/Array.ts
- `union`
- `intersection`
- `difference`
> add set operations to Array

- README.md
> Add a warning about multiple fp-ts versions

- README.md
- docs/Record.md
- dtslint/index.d.ts
- dtslint/index.ts
- dtslint/tsconfig.json
- dtslint/tslint.json
- package-lock.json
- package.json
- src/HKT.ts
- src/Reader.ts
- src/ReaderT.ts
- src/Record.ts
- test/Either.ts
- test/Exception.ts
- test/Foldable.ts
- test/Foldable2v.ts
- test/Option.ts
- test/ReaderTaskEither.ts
- test/Set.ts
- test/State.ts
- test/StateT.ts
- test/TaskEither.ts
- test/tsconfig.json
> Polish: support for constrained domain in Record module, closes #685

- docs/These.md
- package-lock.json
- package.json
- perf/These/fromOptions.ts
- src/These.ts
- test/These.ts
- thisOrBoth
- thatOrBoth
- theseThis
- theseThat
- fromOptions
- fromEither
> New Feature: augment These with

- src/Foldable.ts
- src/Foldable2v.ts
That should make it work.
Note: Sorry for the CI noise; I'm still having some issue with the instersection of well-known-but-I-dont-remember issue with running tests because of Localstorage and I-m-out-of-time-before-lunch-and-using-the-CI-optimistically.
> fix compile issue with typescript@next (fixes #704)

- src/Const.ts
- src/Either.ts
- src/FreeGroup.ts
- src/Identity.ts
- src/Option.ts
- src/Pair.ts
- src/Record.ts
- src/Set.ts
- src/Setoid.ts
- src/StrMap.ts
- src/These.ts
- src/Tree.ts
- src/Tuple.ts
- src/Validation.ts
- test/Setoid.ts
> setoid use strict equality test optimisation (fixes #699)

- src/Array.ts
- src/NonEmptyArray.ts
@gcanti 
I cannot run the tests because of typescript@next incompatibilities.
Anyway let's discuss the goal of the changes first.
> recycle array and nonemptyarray on noop inserts (fixes #702)

- dtslint/index.ts
- src/Monoid.ts
- src/Record.ts
- src/Semigroup.ts
- test/Monoid.ts
- Semigroup.getDictionarySemigroup
- Monoid..getDictionaryMonoid
- Record.getSetoid
- Record.getMonoid
> New Feature: add Record overloadings to

- src/Array.ts
- src/Foldable2v.ts
- src/Set.ts
- test/Array.ts
- test/Set.ts
> Make member function signatures more consistent

- src/Unfoldable.ts
> fix Unfoldable.replicate overloading

- tsconfig.json
> Change module system to UMD 

- docs/Applicative.md
- src/Applicative.ts
> Docs: Add code highlight for applicative's interchange law

- ramda.md
> Docs: fix broken links on Ramda comparison table.

- README.md
Add waveguide to ecosystem libraries.
> Add waveguide to ecosystem libraries.

- docs/modules/NonEmptyArray2v.ts.md
- dtslint/ts3.0/index.ts
- src/NonEmptyArray.ts
- src/NonEmptyArray2v.ts
- src/index.ts
- test/NonEmptyArray.ts
- test/NonEmptyArray2v.ts
@yawaramin @sledorze here's a candidate implementation, could you please review?
> Experimental: type level non empty arrays

- docs/recipes/HKT.md
- docs/recipes/equality.md
- docs/recipes/interoperability.md
- docs/recipes/numbers.md
- docs/recipes/ordering.md
- docs/recipes/purescript.md
- docs/recipes/ramda.md
I'm still trying to find the right tone, content, and structure, so these might be adjusted in the future. However, they've shown me some things that would need to be covered in a tutorial, which I might start writing next.
Because these are "recipes", I tried to keep the explanations to a minimum: the code should be copy-pasteable and not more at this point. Explanations will follow in different sections of the docs.
Some examples are already well documented in, say, the `Option` documentation page, but for people not knowing where to look those would be unfindable. This is why recipes provide an alternative entry point. Let's see where this goes …
> New recipes: equality, ordering, numbers

- docs/recipes/HKT.md
- docs/recipes/async.md
- docs/recipes/interoperability.md
- docs/recipes/purescript.md
- docs/recipes/ramda.md
Added an "async" recipe to clarify how to solve common problems. This should clarify questions like these: https://github.com/gcanti/fp-ts/pull/784
> Examples of using Task and TaskEither

- src/Array.ts
- src/NonEmptyArray2v.ts
- test/NonEmptyArray2v.ts
> add cons/snoc to nonEmptyArray (fixes #800)

- docs/modules/TaskEither.ts.md
- src/TaskEither.ts
- test/TaskEither.ts
Add `getOrElse` to `TaskEither`.
> Add get or else to task either

- docs/modules/index.md
- docs/type-classes.dot
- docs/type-classes.svg
I added Magma to the type classes diagram and to the index. I _think_ it is in the right place in the diagram, but a second pair of eyes would certainly help :)
> Document Magma

- docs/recipes/ramda.md
Added more similarities to Ramda and fixed some broken links.
> Docs Ramda

- docs/faq.md
- docs/introduction/core-concepts.md
- docs/recipes/async.md
Work in progress to collect several smaller changes to the documentation.
> Docs: various tweaks

- dtslint/ts3.4/index.ts
- src/Apply.ts
- src/ChainRec.ts
- src/Either.ts
- src/Exception.ts
- src/Identity.ts
- src/TaskEither.ts
- test/Apply.ts
- test/Either.ts
- test/EitherT.ts
- test/FreeGroup.ts
- test/Map.ts
- test/Set.ts
- test/Tuple.ts
- test/Validation.ts
> Breaking Change: change type parameters of Either.left and Either.right, closes #543

- src/function.ts
> Rewrite Array<any> to unknown[]

- tsconfig.es6.json
> Don't set `target: es6` in tsconfig.es6.json

- src/Record.ts
> Added some documentation to Record.ts

- src/IOEither.ts
- test/IOEither.ts
> Add `foldIO` and `foldIOEither` to `IOEither`

- README.md
> Adds syntax highlight

- src/Foldable.ts
> Add reduce to FoldableComposition2C1

- docs/modules/IO.ts.md
- src/IO.ts
Hello and thank you for the great library.
Browsing the documentation i found this snippet of code was not working anymore with fp-ts@2.x.x
> Fix code snippet in IO.ts

- docs/introduction/ecosystem.md
- package-lock.json
> docs: added @nll/datum to ecosystems documentation

- README.md
> Fix 404 in readme

- docs/modules/State.ts.md
- src/State.ts
@pfgray I would love to link your blog post about the state monad, if it's okay with you (feel free to change / suggest the text)
> add link to blog post about state monad

- docs/introduction/upgrade-to-v2.md
> fix option chain in migration guide

- package-lock.json
- src/Alt.ts
- src/Applicative.ts
- src/Apply.ts
- src/Bifunctor.ts
- src/Chain.ts
- src/Compactable.ts
- src/Contravariant.ts
- src/Extend.ts
- src/Filterable.ts
- src/FilterableWithIndex.ts
- src/Foldable.ts
- src/FoldableWithIndex.ts
- src/Functor.ts
- src/FunctorWithIndex.ts
- src/Monad.ts
- src/MonadIO.ts
- src/MonadTask.ts
- src/MonadThrow.ts
- src/Profunctor.ts
- src/Record.ts
- src/Semigroupoid.ts
- src/Store.ts
- src/Traversable.ts
- src/TraversableWithIndex.ts
- src/Tree.ts
- src/Witherable.ts
- src/pipeable.ts
This PR adds several missing 3C definitions and relevant overloads
> Introduce new overloads (mainly xxx3C)

- src/ReaderTask.ts
- src/ReaderTaskEither.ts
- src/index.ts
- test/ReaderTask.ts
- test/ReaderTaskEither.ts
> first stab at 'getReaderTaskValidation'

- CHANGELOG.md
- docs/modules/IOEither.ts.md
- docs/modules/ReaderEither.ts.md
- docs/modules/ReaderTask.ts.md
- docs/modules/ReaderTaskEither.ts.md
- docs/modules/StateReaderTaskEither.ts.md
- docs/modules/Task.ts.md
- docs/modules/TaskEither.ts.md
- src/IOEither.ts
- src/ReaderEither.ts
- src/ReaderTask.ts
- src/ReaderTaskEither.ts
- src/StateReaderTaskEither.ts
- src/Task.ts
- src/TaskEither.ts
- test/IOEither.ts
- test/ReaderEither.ts
- test/ReaderTask.ts
- test/ReaderTaskEither.ts
- test/StateReaderTaskEither.ts
- test/Task.ts
- test/TaskEither.ts
RE: https://github.com/gcanti/fp-ts/issues/1049#issuecomment-566923339
> add some kleisli chains

- CHANGELOG.md
- docs/modules/function.ts.md
- dtslint/ts3.5/index.ts
- src/function.ts
- test/function.ts
> add tupled / untupled functions, closes #1062

- docs/modules/Either.ts.md
- src/Either.ts
- test/Either.ts
> make stringifyJSON test compatible with Node.js v12, closes #949

- src/NonEmptyArray.ts
- test/NonEmptyArray.ts
> Add `fold` to `NonEmptyArray`

- docs/recipes/purescript.md
Small issues in examples how to express Haskell/PureScript ideas in TypeScript.
> Fix examples in recipes

- docs/modules/Set.ts.md
- src/Set.ts
- test/Set.ts
Closes #1112
@gcanti Since this is my first contribution to `fp-ts`, please feel free to tell me if there's a problem 🙏
> Add Set.toggle

- docs/learning-resources.md
This adds links to two recent efforts at documenting `fp-ts` outside of the main repository.
> Add community documentation section

- docs/ecosystem.md
Add https://github.com/mikearnaldi/matechs-effect to ecosystem
> Add matechs-effect to ecosystem

- package-lock.json
- package.json
- test/property-test/Option.ts
Related https://github.com/microsoft/TypeScript/pull/37225#issuecomment-595417381
> upgrade to latest fast-check

- docs/modules/IOEither.ts.md
- docs/modules/ReaderEither.ts.md
- docs/modules/ReaderTaskEither.ts.md
- docs/modules/StateReaderTaskEither.ts.md
- docs/modules/TaskEither.ts.md
- dtslint/ts3.5/IOEither.ts
- dtslint/ts3.5/ReaderEither.ts
- dtslint/ts3.5/ReaderTaskEither.ts
- dtslint/ts3.5/StateReaderTaskEither.ts
- dtslint/ts3.5/TaskEither.ts
- src/IOEither.ts
- src/ReaderEither.ts
- src/ReaderTaskEither.ts
- src/StateReaderTaskEither.ts
- src/TaskEither.ts
- **New Feature**
- `IOEither`
- add `chainEitherKW`
- `ReaderEither`
- add `chainEitherKW`
- `ReaderTaskEither`
- add `chainEitherKW`
- add `chainTaskEitherKW`
- add `chainIOEitherKW`
- `StateReaderTaskEither`
- add `chainEitherKW`
- add `chainTaskEitherKW`
- add `chainReaderTaskEitherKW`
- add `chainIOEitherKW`
- `TaskEither`
- add `chainEitherKW`
- add `chainIOEitherKW`
> add KW variants

- docs/modules/ReaderTask.ts.md
- src/ReaderTask.ts
Followed the implementation in Reader / ReaderTaskEither
> Add chainW to ReaderTask

- docs/modules/Either.ts.md
- src/Either.ts
Fixes https://github.com/gcanti/fp-ts/issues/1251
> Refine `Either.parseJSON` return type

- docs/modules/Array.ts.md
- docs/modules/Option.ts.md
- docs/modules/ReadonlyArray.ts.md
- docs/modules/ReadonlyRecord.ts.md
- docs/modules/Record.ts.md
- src/Array.ts
- src/Option.ts
- src/ReadonlyArray.ts
- src/ReadonlyRecord.ts
- src/Record.ts
Seems to be a simple typo that permeated throughout the doc/docstrings.
> Change "Whitherable" → "Witherable"

- docs/modules/Either.ts.md
- docs/modules/IOEither.ts.md
- docs/modules/ReaderEither.ts.md
- docs/modules/ReaderTaskEither.ts.md
- docs/modules/StateReaderTaskEither.ts.md
- docs/modules/TaskEither.ts.md
- src/Either.ts
- src/IOEither.ts
- src/ReaderEither.ts
- src/ReaderTaskEither.ts
- src/StateReaderTaskEither.ts
- src/TaskEither.ts
- test/Either.ts
- test/IOEither.ts
- test/ReaderEither.ts
- test/ReaderTaskEither.ts
- test/StateReaderTaskEither.ts
- test/TaskEither.ts
What should I put in for `@since`?
> Add chainFirstW to Either, TaskEither and ReaderTaskEither

- docs/ecosystem.md
> Add expressive-ts to the ecosystem

- src/Chain.ts
> docs: fix typo in Chain.ts for deriving ap 

- package.json
- src/Reader.ts
https://github.com/gcanti/fp-ts/issues/1317
> R.Strong Export for Fanout

- docs/ecosystem.md
I am not the author of this library but have been using it successfully in production. I think the author did a good job creating a simple functional wrapper using fp-ts around the fetch utility.
**Note**. If you want to send a PR …
> Update ecosystem to include fp-fetch

- docs/ecosystem.md
> Add fp-ts-std to ecosystem docs

- docs/ecosystem.md
Add plugin that adds support for fp-ts entities to fastify into Ecosystem doc.
> Add plugin for fastify to ecosystem.md

- src/Array.ts
- src/Either.ts
- src/IO.ts
- src/IOEither.ts
- src/Identity.ts
- src/NonEmptyArray.ts
- src/Option.ts
- src/Ord.ts
- src/Reader.ts
- src/ReaderEither.ts
- src/ReaderTask.ts
- src/ReaderTaskEither.ts
- src/ReadonlyArray.ts
- src/ReadonlyNonEmptyArray.ts
- src/ReadonlyRecord.ts
- src/State.ts
- src/StateReaderTaskEither.ts
- src/Task.ts
- src/TaskEither.ts
- src/Tree.ts
- src/function.ts
I inspected my bundle and discovered a few things being bundled which shouldn't have been. These comments fixed that.
There might be more to fix—I just fixed the ones that were causing me problems.
> Add more `/*#__PURE__*/` comments to improve tree shaking

- docs/modules/Eq.ts.md
- docs/modules/Ord.ts.md
- src/Eq.ts
- src/Ord.ts
- test/Eq.ts
- test/Ord.ts
> Add eqBigInt and ordBigInt

- docs/modules/Tree.ts.md
- src/Tree.ts
- test/Tree.ts
Migrate `Tree.unfoldTreeM` and `Tree.unfoldForestM` from 2.x
> add Tree.unfoldTreeM and Tree.unfoldForestM

- docs/ecosystem.md
> docs: add fp-ts-bigint to ecosystem.md

- docs/modules/Witherable.ts.md
- src/Witherable.ts
- test/Witherable.ts
> Add filterE utils to Witherable

- docs/modules/EitherT.ts.md
- docs/modules/IOEither.ts.md
- docs/modules/ReaderEither.ts.md
- docs/modules/ReaderTaskEither.ts.md
- docs/modules/TaskEither.ts.md
- dtslint/ts3.5/IOEither.ts
- dtslint/ts3.5/ReaderEither.ts
- dtslint/ts3.5/ReaderTaskEither.ts
- dtslint/ts3.5/TaskEither.ts
- src/EitherT.ts
- src/IOEither.ts
- src/ReaderEither.ts
- src/ReaderTaskEither.ts
- src/TaskEither.ts
- test/IOEither.ts
- test/ReaderEither.ts
- test/ReaderTaskEither.ts
- test/TaskEither.ts
Refs https://github.com/gcanti/fp-ts/pull/1445#issuecomment-808323185
> Backport EitherT orElseFirst and orLeft

- docs/modules/ReadonlyArray.ts.md
- src/ReadonlyArray.ts
> docs: add ReadonlyArray.lefts to category combinators

- CHANGELOG.md
- package.json
- src/Record.ts
@OliverJAsh this should fix the last issue
> version 2.10.2

- docs/modules/Either.ts.md
- docs/modules/IOEither.ts.md
- docs/modules/ReaderEither.ts.md
- docs/modules/ReaderTaskEither.ts.md
- docs/modules/StateReaderTaskEither.ts.md
- docs/modules/TaskEither.ts.md
- src/Either.ts
- src/IOEither.ts
- src/ReaderEither.ts
- src/ReaderTaskEither.ts
- src/StateReaderTaskEither.ts
- src/TaskEither.ts
> fix altW function signature in all Either modules, fixes #1488

- docs/modules/FromReader.ts.md
- docs/modules/ReaderEither.ts.md
- docs/modules/ReaderTask.ts.md
- docs/modules/ReaderTaskEither.ts.md
- docs/modules/StateReaderTaskEither.ts.md
- src/FromReader.ts
- src/ReaderEither.ts
- src/ReaderTask.ts
- src/ReaderTaskEither.ts
- src/StateReaderTaskEither.ts
- test/ReaderEither.ts
- test/ReaderTaskEither.ts
This P.R. adds the following methods:
- chainFirstReaderK
- chainFirstReaderK
- chainFirstReaderKW
- chainReaderKW
- chainFirstReaderK
- chainFirstReaderKW
- chainReaderKW
- chainFirstReaderK
- chainFirstReaderKW
- chainFirstReaderTaskK
- chainFirstReaderTaskKW
- chainReaderKW
- chainFirstReaderK
- chainFirstReaderKW
- chainReaderKW
> Add FromReader.chainFirstReaderK

- CHANGELOG.md
- docs/modules/ReaderTaskEither.ts.md
- src/ReaderTaskEither.ts
- test/ReaderTaskEither.ts
backport of #1485 for version 2.11
> Add RTE.fromReaderTaskK, RTE.chainReaderTaskK and RTE.chainReaderTaskKW

- CHANGELOG.md
- docs/modules/Array.ts.md
- docs/modules/FromReader.ts.md
- docs/modules/ReaderEither.ts.md
- docs/modules/ReaderTask.ts.md
- docs/modules/ReaderTaskEither.ts.md
- docs/modules/StateReaderTaskEither.ts.md
- src/Array.ts
- src/FromReader.ts
- src/ReaderEither.ts
- src/ReaderTask.ts
- src/ReaderTaskEither.ts
- src/StateReaderTaskEither.ts
- test/ReaderEither.ts
- test/ReaderTaskEither.ts
> Add from reader chain first reader k

- src/ReaderT.ts
This implements the ability to run an effect using the various `From*` type-classes after asking for something from the environment.
I'm happy to add some tests if they seem needed, but I figured that since it's mainly just composition and type-signatures they might not be too important.
> ReaderT asks*K variants

- CHANGELOG.md
- docs/modules/ReaderTaskEither.ts.md
- src/ReaderTaskEither.ts
- test/ReaderTaskEither.ts
This P.R. add these methods in `ReaderTaskEither`:
- `fromReaderEitherK`
- `chainReaderEitherK` / `chainReaderEitherKW`
- `chainFirstReaderEitherK` / `chainFirstReaderEitherKW`
> Add rte chain reader either k

- docs/modules/ReaderT.ts.md
- docs/modules/ReaderTaskEither.ts.md
- src/ReaderTaskEither.ts
- test/ReaderTaskEither.ts
> Add RTE.chainReaderEitherK(W) and RTE.chainFirstReaderEitherK(W)

- CHANGELOG.md
- docs/modules/ReaderTaskEither.ts.md
- src/ReaderTaskEither.ts
- test/ReaderTaskEither.ts
We should have them all on ReaderTaskEither now!
> Add RTE.chainFirstTaskEitherK

- docs/modules/ReaderTaskEither.ts.md
- src/ReaderTaskEither.ts
- test/ReaderTaskEither.ts
> Add RTE.add-rte-chainFirstTaskEitherK(W)

- docs/modules/StateT.ts.md
- src/StateT.ts
> fix: StateT.fromF for Functor1 should generate StateT1

- docs/ecosystem.md
- Adds the section "Tooling" (docs-ts + a new package "create-fp-ts-lib")
- Adds two libraries (fp-ts-sized-vectors, fp-ts-number-instances)
> Enhance ecosystem

- README.md
It's just a single line documentation change, tests checklist doesn't apply.
> Fixes #1516

- src/Eq.ts
> Update Eq.ts -> Eq<A>['equals']

- CHANGELOG.md
- README.md
- docs/index.md
- change build badge to github action
- add new line for better view in `CHANGELOG.md`
- change links of FP sites
> update doc files

- README.md
Got it from here https://github.com/Functional-Programming-Slack/community/issues/34#issuecomment-873663123.
Closes https://github.com/gcanti/fp-ts/issues/1516.
> Update FP chat invitation link

- src/struct.ts
> struct: alias _.hasOwnProperty to _.has for evolve

- docs/modules/ReadonlyArray.ts.md
- src/ReadonlyArray.ts
Closes https://github.com/gcanti/fp-ts/issues/1573
> ReadonlyArray: fix takeRight category

- docs/modules/ReadonlyRecord.ts.md
- docs/modules/Record.ts.md
- src/ReadonlyRecord.ts
- src/Record.ts
- test/ReadonlyRecord.ts
- test/Record.ts
* Added `Record.toEntries` and `Record.fromEntries`, to facilitate a common need of folks coming over from 'normal' JS.
> Added Record toEntries, fromEntries

- docs/ecosystem.md
> Add fp-ts-react-stable-hooks to ecosystem markdown

- docs/modules/Task.ts.md
- src/Task.ts
Fixes #1626 changing tests to don't check order execution beahvior.
> Fixed task delay test

- docs/modules/TaskEither.ts.md
- src/TaskEither.ts
- test/TaskEither.ts
This was missing.
I can do the port to the version 3 when this one is merged.
> Add taskEither.chainFirstEitherK

- docs/modules/pipeable.ts.md
- src/pipeable.ts
> docs: fix `function.pipe` link docs of `pipeable.pipe`

- docs/modules/ReaderTask.ts.md
- dtslint/ts3.5/ReaderTask.ts
- src/ReaderTask.ts
- test/ReaderTask.ts
Copied from https://github.com/gcanti/fp-ts-contrib/pull/92.
> Add ReaderIO transformation/combinators to ReaderTask

- docs/modules/ReaderTaskEither.ts.md
- dtslint/ts3.5/ReaderTaskEither.ts
- src/ReaderTaskEither.ts
- test/ReaderTaskEither.ts
Copied from https://github.com/gcanti/fp-ts-contrib/pull/90.
> Add ReaderIO constructors/combinators to ReaderTaskEither

- test/Array.ts
- test/ReadonlyArray.ts
- test/ReadonlyNonEmptyArray.ts
- test/string.ts
Add tests isString and isOutOfBound.
> Add tests isString and isOutOfBound

- docs/learning-resources.md
Hello, I am excited to share with you my contribution to the Functional Programming community. I'm creating a series of tutorial videos on YouTube called "Functional Programming with TypeScript," which gradually teaches viewers to create a library like fp-ts while also introducing the fundamentals of Functional Programming. These videos provide a unique and engaging way for users to learn FP with TypeScript and create their own libraries. I believe that these videos would be a valuable addition to the learning resources for fp-ts users and enthusiasts. I would be honored to have the opportunity to contribute to the amazing work of fp-ts and to share my knowledge and expertise with the community. Thank you for your consideration.
- Add a line in Learning Resources to [Functional …
> Enhancing the Learning Resources for fp-ts: "Functional Programming with TypeScript"

- docs/modules/ReaderEither.ts.md
- docs/modules/ReaderIO.ts.md
- docs/modules/ReaderTask.ts.md
- docs/modules/ReaderTaskEither.ts.md
- docs/modules/StateReaderTaskEither.ts.md
- src/FromReader.ts
- src/ReaderEither.ts
- src/ReaderIO.ts
- src/ReaderTask.ts
- src/ReaderTaskEither.ts
- src/StateReaderTaskEither.ts
- test/ReaderEither.ts
- test/ReaderIO.ts
- test/ReaderTask.ts
- test/ReaderTaskEither.ts
- test/StateReaderTaskEither.ts
> feat: tapReader

- docs/modules/ReaderEither.ts.md
- docs/modules/ReaderIO.ts.md
- docs/modules/ReaderTask.ts.md
- docs/modules/ReaderTaskEither.ts.md
- docs/modules/StateReaderTaskEither.ts.md
- docs/modules/TaskEither.ts.md
- docs/modules/TaskOption.ts.md
- src/ReaderEither.ts
- src/ReaderIO.ts
- src/ReaderTask.ts
- src/ReaderTaskEither.ts
- src/StateReaderTaskEither.ts
- src/TaskEither.ts
- src/TaskOption.ts
- src/internal.ts
- test/ReaderEither.ts
- test/ReaderIO.ts
- test/ReaderTask.ts
- test/ReaderTaskEither.ts
- test/StateReaderTaskEither.ts
- test/TaskEither.ts
- test/TaskOption.ts
#1851 
- `flatMapTask` and `flatMapReader` added
- I found two mistakes from my previous PRs 
- I used `this['Out']` instead of `this['In']` for the `R` type parameter for `ReaderIO`
- `SRTE.chainReaderKW` was accidentally aliased to `tapReader`
> Add `flatMapTask` & `flatMapReader`

- docs/modules/ReaderTask.ts.md
- docs/modules/ReaderTaskEither.ts.md
- src/ReaderTask.ts
- src/ReaderTaskEither.ts
- test/ReaderTask.ts
- test/ReaderTaskEither.ts
> feat: flatMapReaderIO

- docs/modules/ReaderTaskEither.ts.md
- src/ReaderTaskEither.ts
> Fix type signature of RTE.tapReaderIO

- src/Identity.ts
- test/Identity.ts
> Add tap for Identity

- docs/modules/ReaderTask.ts.md
- src/ReaderTask.ts
- test/ReaderTask.ts
This PR introduces `apFirstW` and `apSecondW` to `ReaderTask` module.
> Add `apFirstW` and `apSecondW` to `ReaderTask`
